### ISSUE TITLE
Doesn't run on Linux

### ISSUE THREAD

**Issue by UndarkAido** [narrowtux/SmartModInserter#3]
All I get is this:

```
$ ./FactorioModManager-0.2.1.jar 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
java.lang.NullPointerException
    at com.narrowtux.fmm.Main.start(Main.java:40)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:863)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$50(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by giodamelio** [comment]
This is happening for me too

**Comment by UndarkAido** [comment]
He doesn't plan on fixing it; we'll have to wait on official mmo's support.
